name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: asyncapi-bot
          GIT_AUTHOR_EMAIL: derberg@wp.pl
          GIT_COMMITTER_NAME: asyncapi-bot
          GIT_COMMITTER_EMAIL: derberg@wp.pl
        run: npm run release
  release-docker:
    name: Release to Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get version from package.json
        id: extractver
        run: echo "::set-output name=version::$(npm run get-version --silent)"
      - name: echo version
        run: echo "to dziala ${{ steps.extractver.outputs.version }}"