name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: Lukasz Gornicki
          GIT_AUTHOR_EMAIL: lpgornicki@gmail.com
          GIT_COMMITTER_NAME: Lukasz Gornicki
          GIT_COMMITTER_EMAIL: lpgornicki@gmail.com
        run: npm run release